version: "3.8"

services:
  postgres_source:
    image: postgres:14
    container_name: demo-postgres-source
    restart: always
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopassword
      POSTGRES_DB: healthdata
    ports:
      - "5433:5432"
    volumes:
      - postgres_source_data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d

  postgres_analytics:
    image: postgres:14
    container_name: demo-postgres-analytics
    restart: always
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: demopassword
      POSTGRES_DB: analytics
    ports:
      - "5432:5432"
    volumes:
      - postgres_analytics_data:/var/lib/postgresql/data

volumes:
  postgres_source_data:
  postgres_analytics_data:
