x-redash-service: &redash-service
  image: redash/redash:latest
  platform: linux/amd64
  depends_on:
    - postgres
    - redis
  env_file: .env
  restart: unless-stopped

services:
  server:
    <<: *redash-service
    command: server
    ports:
      - "5005:5000"
    environment:
      REDASH_WEB_WORKERS: 4

  scheduler:
    <<: *redash-service
    command: scheduler
    depends_on:
      - server

  scheduled_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1

  adhoc_worker:
    <<: *redash-service
    command: worker
    depends_on:
      - server
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2

  worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "periodic,emails,default"
      WORKERS_COUNT: 1

  redis:
    image: redis:7-alpine
    restart: unless-stopped

  postgres:
    image: postgres:14
    platform: linux/amd64
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    env_file: .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5438:5432"

volumes:
  postgres_data:
